# Generated by Django 2.2.9 on 2020-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('İsim', models.CharField(max_length=100)),
                ('Soyisim', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=100)),
                ('Dogum_Tarihi', models.DateTimeField()),
                ('Okulu', models.CharField(max_length=100)),
                ('Bolumu', models.CharField(max_length=100)),
                ('Sinifi', models.CharField(choices=[('h', 'Hazırlık'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1, max_length=1)),
            ],
        ),
    ]
