# Generated by Django 2.2.9 on 2020-01-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ogrenci', '0002_auto_20200101_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='Sinifi',
            field=models.CharField(choices=[('h', 'Hazırlık'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1),
        ),
    ]
