# Generated by Django 2.2.9 on 2020-01-01 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ogrenci', '0004_auto_20200101_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogrenci',
            old_name='Bolumu',
            new_name='Bölümü',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='Dogum_Tarihi',
            new_name='Doğum_Tarihi',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='Sinifi',
            new_name='Sınıfı',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='Isim',
            new_name='İsim',
        ),
    ]
