# Generated by Django 2.2.9 on 2020-01-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ogrenci', '0005_auto_20200101_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='E_mail',
            field=models.EmailField(max_length=100),
        ),
    ]
